// Generated by @pragmatic-lab/todl read-client codegen. Do not edit.
import { FrozenRepository, EntityBase } from "../../../index.js";

export class TechCatalog extends FrozenRepository {
  protected override createEntity(id: string): EntityBase {
    switch (this.resolve(id)?.typeOf) {
      case "billing": return new Billing(this, id);
      case "location": return new Location(this, id);
      case "technology": return new Technology(this, id);
      default: return super.createEntity(id);
    }
  }

  get billings(): readonly Billing[] {
    return this.instancesOf("billing").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as Billing);
  }

  get locations(): readonly Location[] {
    return this.instancesOf("location").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as Location);
  }

  get technologies(): readonly Technology[] {
    return this.instancesOf("technology").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as Technology);
  }

  get stack(): readonly Technology[] {
    return this.termsOf("stack").map((id) => this.entity(id) as Technology);
  }
}

export class Billing extends EntityBase {
  get label(): string { return this.field("label") as string; }
}

export class Location extends EntityBase {
  get label(): string { return this.field("label") as string; }
}

export class Technology extends EntityBase {
  get label(): string { return this.field("label") as string; }
  get availableIn(): readonly Location[] { return this.refs("available-in") as Location[]; }
  get billing(): Billing | undefined { return this.ref("billing") as Billing | undefined; }
}
