/**
 * Read-client codegen (design spec §6, Component C). Reflects a resolved
 * {@link Repository} (concepts, taxonomies, `effectiveSchema`) and emits a `.ts`
 * source with a typed package class (per-concept + per-taxonomy collection
 * accessors, routed construction) and one typed entity class per concept
 * (scalar + reference getters). Output is deterministic — everything sorted by id.
 */

import { MetaKind } from "../model/kinds.js";
import { Cardinality, type NodeId } from "../model/graph.js";
import { Repository } from "../model/model.js";
import { pascalCase, camelCase, pluralize, allocateNames } from "./naming.js";

export interface ReadClientOptions {
  /** Artifact id (kebab); becomes the PascalCase package class name. */
  name: string;
  /** Import module specifier for the todl runtime. Defaults to the package name. */
  importSpecifier?: string;
}

/** True when `typeId` names a concept or taxonomy (→ reference); false for a primitive. */
export function isReferenceType(repo: Repository, typeId: string): boolean {
  const kind = repo.resolve(typeId)?.typeOf;
  return kind === MetaKind.Concept || kind === MetaKind.Taxonomy;
}

interface RefMember {
  name: string;
  targetPascal: string;
  many: boolean;
}

function scalarTsType(typeId: string): string {
  if (typeId === "integer" || typeId === "number") return "number";
  if (typeId === "boolean") return "boolean";
  return "string";
}

function isMany(cardinality: Cardinality): boolean {
  return cardinality === Cardinality.Many || cardinality === Cardinality.NonEmpty;
}

/** The PascalCase entity type a reference member resolves to. */
function targetPascal(repo: Repository, typeId: string): string {
  if (repo.resolve(typeId)?.typeOf === MetaKind.Taxonomy) {
    return pascalCase(repo.represents(typeId)[0] ?? typeId);
  }
  return pascalCase(typeId);
}

export function generateReadClient(repo: Repository, options: ReadClientOptions): string {
  const importSpecifier = options.importSpecifier ?? "@pragmatic-lab/todl";

  const concepts = repo
    .allNodes()
    .filter((n) => n.typeOf === MetaKind.Concept)
    .map((n) => n.id)
    .sort();
  const taxonomies = repo
    .allNodes()
    .filter((n) => n.typeOf === MetaKind.Taxonomy)
    .map((n) => n.id)
    .sort();

  // Force the collision check across all generated entity-class names.
  allocateNames(concepts, pascalCase);

  const header =
    `// Generated by @pragmatic-lab/todl read-client codegen. Do not edit.\n` +
    `import { FrozenRepository, EntityBase } from "${importSpecifier}";`;

  const packageClass = emitPackageClass(pascalCase(options.name), concepts, taxonomies, repo);
  const entityClasses = concepts.map((c) => emitEntityClass(c, repo));

  return [header, packageClass, ...entityClasses].join("\n\n") + "\n";
}

function emitPackageClass(
  className: string,
  concepts: readonly NodeId[],
  taxonomies: readonly NodeId[],
  repo: Repository,
): string {
  const cases = concepts.map((c) => `      case "${c}": return new ${pascalCase(c)}(this, id);`).join("\n");
  const createEntity =
    `  protected override createEntity(id: string): EntityBase {\n` +
    `    switch (this.resolve(id)?.typeOf) {\n` +
    `${cases}\n` +
    `      default: return super.createEntity(id);\n` +
    `    }\n` +
    `  }`;

  const conceptGetters = concepts.map(
    (c) =>
      `  get ${pluralize(camelCase(c))}(): readonly ${pascalCase(c)}[] {\n` +
      `    return this.instancesOf("${c}").filter((id) => !this.isClass(id)).map((id) => this.entity(id) as ${pascalCase(c)});\n` +
      `  }`,
  );
  const taxonomyGetters = taxonomies.map((t) => {
    const rep = pascalCase(repo.represents(t)[0] ?? t);
    return (
      `  get ${camelCase(t)}(): readonly ${rep}[] {\n` +
      `    return this.termsOf("${t}").map((id) => this.entity(id) as ${rep});\n` +
      `  }`
    );
  });

  const getters = [...conceptGetters, ...taxonomyGetters].join("\n\n");
  return `export class ${className} extends FrozenRepository {\n${createEntity}\n\n${getters}\n}`;
}

function emitEntityClass(concept: NodeId, repo: Repository): string {
  const schema = repo.effectiveSchema(concept);

  const scalarGetters = schema.fields
    .filter((f) => !isReferenceType(repo, f.type))
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
    .map((f) => {
      const ts = scalarTsType(f.type);
      return `  get ${camelCase(f.name)}(): ${ts} { return this.field("${f.name}") as ${ts}; }`;
    });

  const refMembers: RefMember[] = [
    ...schema.fields
      .filter((f) => isReferenceType(repo, f.type))
      .map((f) => ({ name: f.name, targetPascal: targetPascal(repo, f.type), many: isMany(f.cardinality) })),
    ...schema.relationships.map((r) => ({
      name: r.name,
      targetPascal: pascalCase(r.target),
      many: isMany(r.cardinality),
    })),
  ].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));

  const refGetters = refMembers.map((m) =>
    m.many
      ? `  get ${camelCase(m.name)}(): readonly ${m.targetPascal}[] { return this.refs("${m.name}") as ${m.targetPascal}[]; }`
      : `  get ${camelCase(m.name)}(): ${m.targetPascal} | undefined { return this.ref("${m.name}") as ${m.targetPascal} | undefined; }`,
  );

  const getters = [...scalarGetters, ...refGetters].join("\n");
  return `export class ${pascalCase(concept)} extends EntityBase {\n${getters}\n}`;
}
