/**
 * JS-module emitter (design spec §7.3) — project a TODL {@link Model}'s
 * ontology tier to a legacy `<slug>.meta.js` ES module, the shape the browser
 * runtime (`todl-runtime` / Mural / Plexus) consumes. Faithful to the legacy
 * `tools/todl/js_emit.py` contract:
 *
 *   - `export class <Pascal> extends ModelElement` per concept, carrying a
 *     `static schema = { kind, fields, relationships }`.
 *   - `export const <Pascal>` per enum: an `{ slug, values, has() }` table.
 *   - `export const <camel>` registry aggregating concept schemas,
 *     data-driven constructors, and enum tables — what the runtime queries.
 *
 * Generated code is machine output: no JSDoc, no typed getters. Classes are
 * thin schema vehicles over the hand-authored `ModelElement` base.
 */

import { Cardinality } from "../model/graph.js";
import { MetaKind } from "../model/kinds.js";
import type { Model, FieldSchema, RelationshipSchema } from "../model/model.js";

/** Default relative import to the `ModelElement` base the emitted classes extend. */
const DEFAULT_RUNTIME_IMPORT = "todl-runtime/model-element.js";

export interface MetaModuleOptions {
  /** The meta-model slug, e.g. `bpmn`. Names the registry and the `slug` field. */
  slug: string;
  /** The root concept id, emitted as `rootConcept` when set. */
  rootConcept?: string;
  /** Override the `import` path to the `ModelElement` base. */
  runtimeImport?: string;
  /** Override the registry export name (defaults to camelCase of `slug`). */
  registryName?: string;
}

/** Emit a bundled `<slug>.meta.js` ES module from `model`'s ontology tier. */
export function toMetaModule(model: Model, options: MetaModuleOptions): string {
  const runtimeImport = options.runtimeImport ?? DEFAULT_RUNTIME_IMPORT;
  const registryName = options.registryName ?? camelCase(options.slug);

  const concepts = [...model.instancesOf(MetaKind.Concept)].sort();
  const enums = [...model.instancesOf(MetaKind.Enum)].sort();

  const lines: string[] = [
    "// AUTO-GENERATED — do not edit.",
    `// Meta-model: ${options.slug}`,
    "// Generated by @pragmatic-lab/todl js-module emitter.",
    "//",
    "// Bundles every concept + enum from the ontology into a single ES module:",
    "// typed-class declarations, enum tables, and a registry export the runtime",
    "// queries to introspect the schema.",
    "",
    `import { ModelElement } from ${jsStr(runtimeImport)};`,
    "",
    "// ── Concepts ──────────────────────────────────────────────",
    "",
  ];

  for (const concept of concepts) {
    lines.push(emitConcept(model, concept));
    lines.push("");
  }

  if (enums.length > 0) {
    lines.push("// ── Enums ─────────────────────────────────────────────────");
    lines.push("");
    for (const enumId of enums) {
      lines.push(emitEnum(model, enumId));
      lines.push("");
    }
  }

  lines.push("// ── Registry ──────────────────────────────────────────────");
  lines.push("");
  lines.push(emitRegistry(registryName, options.slug, options.rootConcept ?? null, concepts, enums));
  lines.push("");

  return lines.join("\n");
}

// ── Concept emission ──────────────────────────────────────────────────

function emitConcept(model: Model, concept: string): string {
  const schema = model.schemaOf(concept);
  const cls = pascalCase(concept);
  const i = "    ";
  const lines: string[] = [];
  lines.push(`export class ${cls} extends ModelElement {`);
  lines.push(`${i}static schema = {`);
  lines.push(`${i}${i}kind: ${jsStr(concept)},`);

  if (schema.fields.length > 0) {
    lines.push(`${i}${i}fields: {`);
    for (const field of schema.fields) {
      lines.push(`${i}${i}${i}${jsKey(field.name)}: { ${fieldEntries(field).join(", ")} },`);
    }
    lines.push(`${i}${i}},`);
  }

  if (schema.relationships.length > 0) {
    lines.push(`${i}${i}relationships: {`);
    for (const rel of schema.relationships) {
      lines.push(`${i}${i}${i}${jsKey(rel.name)}: { ${relationshipEntries(rel).join(", ")} },`);
    }
    lines.push(`${i}${i}},`);
  }

  lines.push(`${i}};`);
  lines.push("}");
  return lines.join("\n");
}

function fieldEntries(field: FieldSchema): string[] {
  const entries = [`type: ${jsStr(field.type)}`];
  const card = fieldCardinalityText(field.cardinality);
  if (card !== null) entries.push(`cardinality: ${jsStr(card)}`);
  const resolves = resolvesHint(field.type, field.cardinality);
  if (resolves !== null) entries.push(`resolves: ${jsStr(resolves)}`);
  return entries;
}

function relationshipEntries(rel: RelationshipSchema): string[] {
  return [`target: ${jsStr(rel.target)}`, `cardinality: ${jsStr(relationshipCardinalityText(rel.cardinality))}`];
}

// ── Enum emission ─────────────────────────────────────────────────────

function emitEnum(model: Model, enumId: string): string {
  const name = pascalCase(enumId);
  const i = "    ";
  const lines: string[] = [`export const ${name} = {`];
  lines.push(`${i}slug: ${jsStr(enumId)},`);
  lines.push(`${i}values: {`);
  for (const caseId of model.instancesOf(enumId)) {
    const node = model.resolve(caseId);
    const parts = [`id: ${jsStr(caseId)}`];
    const label = node?.attrs.get("label");
    if (typeof label === "string") parts.push(`label: ${jsStr(label)}`);
    const description = node?.attrs.get("description");
    if (typeof description === "string") parts.push(`description: ${jsStr(description)}`);
    lines.push(`${i}${i}${jsKey(caseId)}: { ${parts.join(", ")} },`);
  }
  lines.push(`${i}},`);
  // has() — true if `value` (an id, an array, or a `|`/`+`/`,`-joined combo)
  // carries `member`. Ported verbatim from the legacy contract.
  lines.push(`${i}has(value, member) {`);
  lines.push(`${i}${i}if (value == null) return false;`);
  lines.push(`${i}${i}if (Array.isArray(value)) return value.includes(member);`);
  lines.push(`${i}${i}if (typeof value === 'string') {`);
  lines.push(`${i}${i}${i}return value.split(/[|+,]/).map(s => s.trim()).includes(member);`);
  lines.push(`${i}${i}}`);
  lines.push(`${i}${i}return value === member;`);
  lines.push(`${i}},`);
  lines.push("};");
  return lines.join("\n");
}

// ── Registry emission ─────────────────────────────────────────────────

function emitRegistry(
  registryName: string,
  slug: string,
  rootConcept: string | null,
  concepts: readonly string[],
  enums: readonly string[],
): string {
  const i = "    ";
  const lines: string[] = [`export const ${registryName} = {`];
  lines.push(`${i}slug: ${jsStr(slug)},`);
  if (rootConcept !== null) lines.push(`${i}rootConcept: ${jsStr(rootConcept)},`);

  lines.push(`${i}concepts: {`);
  for (const concept of concepts) {
    lines.push(`${i}${i}${jsKey(concept)}: ${pascalCase(concept)}.schema,`);
  }
  lines.push(`${i}},`);

  lines.push(`${i}constructors: {`);
  for (const concept of concepts) {
    const cls = pascalCase(concept);
    lines.push(
      `${i}${i}${jsKey(concept)}: data => { const o = new ${cls}(); ` +
        `if (data) for (const [k, v] of Object.entries(data)) o.set(k, v); return o; },`,
    );
  }
  lines.push(`${i}},`);

  lines.push(`${i}enums: {`);
  for (const enumId of enums) {
    lines.push(`${i}${i}${jsKey(enumId)}: ${pascalCase(enumId)},`);
  }
  lines.push(`${i}},`);

  lines.push("};");
  return lines.join("\n");
}

// ── Cardinality + resolution hints ────────────────────────────────────

/** Field cardinality text; `null` for required-single (the omitted default). */
function fieldCardinalityText(card: Cardinality): string | null {
  switch (card) {
    case Cardinality.One:
      return null;
    case Cardinality.Optional:
      return "0..1";
    case Cardinality.Many:
      return "*";
    case Cardinality.NonEmpty:
      return "1..*";
  }
}

/** Relationship cardinality text; relationships always carry an explicit value. */
function relationshipCardinalityText(card: Cardinality): string {
  return fieldCardinalityText(card) ?? "1..1";
}

/** Coarse resolver classification for name-ref-typed fields. */
function resolvesHint(type: string, card: Cardinality): string | null {
  if (type !== "identifier" && type !== "slug") return null;
  return card === Cardinality.Many || card === Cardinality.NonEmpty ? "list-of-name-ref" : "name-ref";
}

// ── String helpers ────────────────────────────────────────────────────

/** `component-category` → `ComponentCategory`. */
function pascalCase(slug: string): string {
  return slug
    .split("-")
    .map((part) => (part.length > 0 ? part[0]!.toUpperCase() + part.slice(1) : part))
    .join("");
}

/** `enterprise-architecture` → `enterpriseArchitecture`. */
function camelCase(slug: string): string {
  const pascal = pascalCase(slug);
  return pascal.length > 0 ? pascal[0]!.toLowerCase() + pascal.slice(1) : pascal;
}

/** JS double-quoted string literal with control characters escaped. */
function jsStr(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

/** A JS object key — bare when a valid identifier, quoted otherwise. */
function jsKey(value: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : jsStr(value);
}
